---
# data is stored in a variable whose name is the CSV file name without the extension
- include_csv:
    src: "{{sta_serverList}}"
    outname: "my_sta_serverList"

- include_csv:
    src: "{{sta_appMapping}}"
    outname: "my_sta_appMapping"

# sta_serverList is the name of the csv.
# For compatibility of old versions, match is changed to match

- name: "Set Serverlist CSV variables"
  set_fact:
    cluster_master_grp: "{{ my_sta_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"
    dep_server_grp:     "{{ my_sta_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"
    ind_slave_grp:      "{{ my_sta_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"
    license_master_grp: "{{ my_sta_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"
    shc_member_grp:     "{{ my_sta_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"

- name: "Set Serverlist Concatenated variables"
  set_fact:
    distributedSearch_uri:  '{% set comma = joiner(",") -%} {% for host in shc_member_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    distributedIndexer_uri: '{% set comma = joiner(",") -%} {% for host in ind_slave_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    dep_server_uri:  '{% set comma = joiner(",") -%} {% for host in dep_server_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    license_master_uri:  '{% set comma = joiner(",") -%} {% for host in license_master_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    indexers_fwd_uri: '{% set comma = joiner(",") -%} {% for host in ind_slave_grp %}{{comma()}}{{host}}:{{fwdPort}}{% endfor %}'
