---
- import_tasks: roles/common/set_variables/set_variables_{{inputTag}}.yml
  tags: [set_variables]

- import_tasks: pre_build_apps.yml
  tags: [pre_build_apps]

- import_tasks: build_apps_specific.yml
  tags: [build_apps_specific]
