---
- import_tasks: roles/common/set_variables/set_variables_sta.yml
  tags: [set_variables_sta]

- import_tasks: roles/common/set_variables/set_variables_uf.yml
  tags: [set_variables_uf]

- import_tasks: pre_build_sta_apps.yml
  tags: [pre_build_sta_apps]

- import_tasks: pre_build_uf_apps.yml
  tags: [pre_build_uf_apps]

- import_tasks: build_sta_apps_specific.yml
  tags: [build_es_apps_specific]

- import_tasks: build_uf_apps_specific.yml
  tags: [build_uf_apps_specific]
